In [48]:
import torch
import numpy as np

In [49]:
data = [[1,2], [3,4]]

In [53]:
x_data = torch.tensor(data)

In [54]:
x_data

tensor([[1, 2],
        [3, 4]])

In [55]:
torch.rand(2,3,)

tensor([[0.4994, 0.9267, 0.4411],
        [0.8475, 0.9094, 0.6899]])

In [57]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [64]:
torch.zeros(2,3).device

device(type='cpu')

In [77]:
tt = torch.randint(10, (4,4))
tt

tensor([[2, 8, 2, 8],
        [1, 1, 7, 3],
        [9, 0, 8, 3],
        [4, 4, 0, 0]])

In [100]:
tt[..., 2:] = torch.tensor([[1,2],[3,4], [5,6],[7,8]])

In [108]:
torch.ones(4, 2) * 4

tensor([[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]])

In [119]:
torch.cat([torch.ones(4, 2) * 2, torch.ones(4, 2) * 3, torch.ones(4, 2) * 4], dim=1)

tensor([[2., 2., 3., 3., 4., 4.],
        [2., 2., 3., 3., 4., 4.],
        [2., 2., 3., 3., 4., 4.],
        [2., 2., 3., 3., 4., 4.]])

In [127]:
torch.stack([torch.ones(4, 2) * 2, torch.ones(4, 2) * 3, torch.ones(4, 2) * 4], dim=1)

tensor([[[2., 2.],
         [3., 3.],
         [4., 4.]],

        [[2., 2.],
         [3., 3.],
         [4., 4.]],

        [[2., 2.],
         [3., 3.],
         [4., 4.]],

        [[2., 2.],
         [3., 3.],
         [4., 4.]]])

In [133]:
torch.ones(5,5) + 1.8

tensor([[2.8000, 2.8000, 2.8000, 2.8000, 2.8000],
        [2.8000, 2.8000, 2.8000, 2.8000, 2.8000],
        [2.8000, 2.8000, 2.8000, 2.8000, 2.8000],
        [2.8000, 2.8000, 2.8000, 2.8000, 2.8000],
        [2.8000, 2.8000, 2.8000, 2.8000, 2.8000]])

In [138]:
torch.ones(5, 5).size()

torch.Size([5, 5])

In [148]:
k = torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(1), value=1)

In [149]:
torch.argmax(k)

tensor(1)